# Generated by Django 3.1 on 2022-02-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220206_0621'),
        ('money_internet_affiliate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePage',
            fields=[
                ('pageproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pageproperties')),
                ('name', models.CharField(max_length=50, verbose_name='Affilate Web Page / App : Name')),
                ('url', models.URLField(verbose_name='URL of reference  Web Page / App')),
                ('codename', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.pageproperties',),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('affiliatepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_internet_affiliate.affiliatepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invitelinkhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StepsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_summary', models.TextField()),
                ('content', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_internet_affiliate.steps')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_invitelink', to='money_internet_affiliate.affiliatepage'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
