# Generated by Django 3.1 on 2022-02-08 13:08

from django.db import migrations, models
import money_internet_affiliate.models.affiliate_models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0003_affiliatepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepage',
            name='image_1_alt',
            field=models.CharField(default='', max_length=100, verbose_name='Title of Image (Alt Attribute)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatepage',
            name='image_1_file',
            field=models.ImageField(default='', upload_to=money_internet_affiliate.models.affiliate_models.affiliate_page_product_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatepage',
            name='image_1_filename',
            field=models.CharField(default='', max_length=100, verbose_name='Filename (image 1)'),
            preserve_default=False,
        ),
    ]
