# Generated by Django 3.1 on 2022-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0004_auto_20220208_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepage',
            name='image_1_alt',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Title of Image (Alt Attribute)'),
        ),
        migrations.AlterField(
            model_name='affiliatepage',
            name='image_1_filename',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Filename (image 1)'),
        ),
    ]
