# Generated by Django 3.1 on 2022-02-08 13:10

from django.db import migrations, models
import money_internet_affiliate.models.affiliate_models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0005_auto_20220208_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepage',
            name='image_1_file',
            field=models.ImageField(blank=True, unique=True, upload_to=money_internet_affiliate.models.affiliate_models.affiliate_page_product_path),
        ),
    ]
