# Generated by Django 3.1 on 2022-02-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0006_auto_20220208_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsitem',
            name='name',
            field=models.CharField(default='PAso 1', max_length=50),
            preserve_default=False,
        ),
    ]
