# Generated by Django 3.1 on 2022-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0007_stepsitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepage',
            name='telegram_group_link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
