# Generated by Django 3.1 on 2022-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0008_affiliatepage_telegram_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='invitelinkhistory',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='steps',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='stepsitem',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
