# Generated by Django 3.1 on 2022-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0009_auto_20220209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
        migrations.AlterField(
            model_name='invitelinkhistory',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
        migrations.AlterField(
            model_name='stepsitem',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
    ]
