# Generated by Django 3.1 on 2022-02-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0010_auto_20220209_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='created_country',
            field=models.CharField(default='Polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitelinkhistory',
            name='created_country',
            field=models.CharField(default='Polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='created_country',
            field=models.CharField(default='polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepsitem',
            name='created_country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
