# Generated by Django 3.1 on 2022-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_internet_affiliate', '0011_auto_20220209_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='invitelinkhistory',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='steps',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stepsitem',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
