# Generated by Django 4.0.1 on 2022-02-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclaimer',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
