# Generated by Django 4.0.1 on 2022-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproperties',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=50),
        ),
    ]
