# Generated by Django 4.0.1 on 2022-02-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disclaimer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnippetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ManyToManyField(to='core.SnippetItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pageproperties',
            name='snippet_collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pageproperties_snippetcollection', to='core.snippetcollection'),
            preserve_default=False,
        ),
    ]
