# Generated by Django 4.0.1 on 2022-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_snippetcollection_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetitem',
            name='snippet_collection',
        ),
        migrations.AddField(
            model_name='snippetcollection',
            name='collection',
            field=models.ManyToManyField(to='core.SnippetItem'),
        ),
    ]
