# Generated by Django 4.0.1 on 2022-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_snippetitem_snippet_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetitem',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
