# Generated by Django 4.0.2 on 2022-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_snippetitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproperties',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index Page, Follow All Links'), ('noindex, nofollow', 'No indexed, No follow links'), ('noindex, follow', 'No indexed, Following Links'), ('index, nofollow', 'Indexed, No Following Links'), ('index', 'Just Indexed (Attention)'), ('follow', 'Just Following Links (Attention)'), ('noindex', 'No indexed (Attention)'), ('nofollow', 'No followed links (Attention)')], default='index, follow', max_length=100, verbose_name='Meta Robots'),
        ),
    ]
