# Generated by Django 4.0.2 on 2022-02-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pageproperties_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproperties',
            name='snippet_collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pageproperties_snippetcollection', to='core.snippetcollection'),
        ),
    ]
