# Generated by Django 3.1 on 2022-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageproperties',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='snippetcollection',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='snippetitem',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
