# Generated by Django 3.1 on 2022-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproperties',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
        migrations.AlterField(
            model_name='snippetcollection',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
        migrations.AlterField(
            model_name='snippetitem',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', editable=False),
        ),
    ]
