# Generated by Django 3.1 on 2022-02-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220209_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageproperties',
            name='created_country',
            field=models.CharField(default='Polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippetcollection',
            name='created_country',
            field=models.CharField(default='Polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippetitem',
            name='created_country',
            field=models.CharField(default='Polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_country',
            field=models.CharField(default='Polonia', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
