# Generated by Django 3.1 on 2022-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220209_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproperties',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='snippetcollection',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='snippetitem',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_country',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
