# Generated by Django 4.0.2 on 2022-02-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220209_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
                ('created_country', models.CharField(editable=False, max_length=50)),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
                ('created_country', models.CharField(editable=False, max_length=50)),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pageproperties',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snippetcollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snippetitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ColumnLinkHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
                ('created_country', models.CharField(editable=False, max_length=50)),
                ('position', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=155)),
                ('custom_url', models.CharField(blank=True, max_length=512, null=True)),
                ('use_custom_url', models.BooleanField(default=False)),
                ('headerlink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.headerlink')),
                ('pageproperties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pageproperties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnLinkFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
                ('created_country', models.CharField(editable=False, max_length=50)),
                ('position', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=155)),
                ('custom_url', models.CharField(blank=True, max_length=512, null=True)),
                ('use_custom_url', models.BooleanField(default=False)),
                ('footerlink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.footerlink')),
                ('pageproperties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pageproperties')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
