# Generated by Django 4.0.1 on 2022-01-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pageproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pageproperties')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('core.pageproperties',),
        ),
    ]
